Fix Apple clang bugs (incorrect SHA results on macOS 26.4) (#61)
* Fix Apple clang bugs (incorrect SHA results on macOS 26.4)

#30 attempted to "fix mac", but did so only partially. Interestingly,
this used to work accidentally, but since macOS 26.4 they shipped a new
Apple clang that randomly introduces UB when the code is wrong.

Open-source clang reports:

```
error: invalid variant on expression 'PAGEOFF' (already modified)
```

So, the problem is that _some_ instances of #30 left the `#:lo12:` ELF
syntax in the `#ifdef __APPLE__` branches. Weirdly, not everywhere.
Applying the correct syntax in all Apple branches fixes the problem.

macOS 26.4 Clang version:
```
% clang --version
Apple clang version 21.0.0 (clang-2100.0.123.102)
Target: arm64-apple-darwin25.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Interestingly, the open-source clang starts failing with UNREACHABLE
when asserts are on: https://github.com/llvm/llvm-project/issues/188764

So, maybe Apple clang has some weird build where asserts are disabled,
and the resulting UB from UNREACHABLE then inhibits "already modified".
But I could not reproduce the successful assembly + wrong results on
open-source clang. The old clang (either OSS or Apple) just works fine.
The new clang (OSS) either crashes with UNREACHABLE or raises error.
The new Apple clang succeeds and then has wrong SHA results.

In any case, fixing the relocation syntax gets rid of the bugs.

* Bump copyright years

* Also use proper .const section on Apple for readonly (.rodata is ELF)

* Use local PAGEOFF instead of GOTPAGEOFF across all the files